:toc:


= How to run example application
* Server: run Application.java
* Client: navigate to /angular-frontend and run _ng serve_

= Spring Security Workshop

These are my notes to the course https://www.udemy.com/spring-security-course/learn/v4/overview[The complete Spring Security Developer Course]. Some code examples are from the great project https://www.jhipster.tech[JHipster].

== Introduction
* https://spring.io/projects/spring-security
* handles security as cross-cutting concern: application logic will not be changed by using Spring Security
* doesn't rely on any environment, for example special application server
* all security-features within application, hence application portable to other environments without additional cost of configuration
* two main tasks:
** authentication = making sure that user is who he says he is
** authorization = making sure user can only do what he is allowed to
* offers features against common attack vectors to circumvent authentication and authorization:
** Cross Site Request Forgery (CSRF)
** Session Fixation Prevention
** Clickjacking protection
** Cross Site Scripting (XSS) protection
** Password encoding via hash and salt

== Filtering requests
* = base for authorization: don't let every request resolve
* done with multiple mechanisms like
** URL-based filtering
** filter-chain

=== URL-based filtering
* decision which request URL gets generally filtered in _WebSecurityConfigurerAdapter_
* via Ant-patterns
* in JHipster done in _SecurityConfiguration_:

[source, java]
----
...
public class SecurityConfiguration extends WebSecurityConfigurerAdapter {
...

    @Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring()
            .antMatchers("/api/authenticate");
            .antMatchers(HttpMethod.OPTIONS, "/**")
            .antMatchers("/app/**/*.{js,html}")
            .antMatchers("/i18n/**")
            .antMatchers("/content/**")
            .antMatchers("/h2-console/**")
            .antMatchers("/swagger-ui/index.html")
            .antMatchers("/test/**");
    }

@Override
public void configure(HttpSecurity http) throws Exception {
    http
        .authorizeRequests()
        .antMatchers("/api/register").permitAll()
        .antMatchers("/api/activate").permitAll()
        .antMatchers("/api/authenticate").permitAll()
        .antMatchers("/api/account/reset-password/init").permitAll()
        .antMatchers("/api/account/reset-password/finish").permitAll()
        .antMatchers("/api/**").authenticated()
        .antMatchers("/management/health").permitAll()
        .antMatchers("/management/info").permitAll()
        .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN)
    .and()
        .apply(securityConfigurerAdapter());

}
----

* *attention*: First matcher matching a URL will decide the filtering! Hence, order of matchers important.

=== Filter-Chain
* if request makes it through the URL-filtering, filter-chain is applied
* = Servlet-Filters that are organized in the _SecurityFilterChain_:

[source, java]
----
package org.springframework.security.web;

...

public interface SecurityFilterChain {

	boolean matches(HttpServletRequest request);

	List<Filter> getFilters();
}
----

* provided by Spring via _GenericFilterBean_, which implements _Filter_
* implementations of this bean for example _DelegatingFilterProxy_ (which uses a filter mapping) or, in JHipster, _JWTFilter_ (which uses a JWT to decide if the request is filtered). Both implementations override _doFilter()_:

[source, java]
----
public class JWTFilter extends GenericFilterBean {

    @Override
    public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain)
        throws IOException, ServletException {
        ...
        filterChain.doFilter(servletRequest, servletResponse);
    }
}
----

== class Authentication
* org.springframework.security.core.Authentication = wrapper for user information like credentials and if the user is authenticated
* used throughout Spring Security

== classes AuthenticationManager, Authentication Provider, UserDetailsService
* answers question if valid user
* therefore, needs an _AuthenticationProvider_
* one way of providing authentication: username + password
* this done in _UserDetailService_ = strategy for _AuthenticationProvider_
* in JHipster:

[source, java]
----
...
public class SecurityConfiguration extends WebSecurityConfigurerAdapter {

    private final AuthenticationManagerBuilder authenticationManagerBuilder;

    private final UserDetailsService userDetailsService;

    ...

    @PostConstruct
    public void init() {
        try {
            authenticationManagerBuilder
                .userDetailsService(userDetailsService)
                .passwordEncoder(passwordEncoder());
        } catch (Exception e) {
            throw new BeanInitializationException("Security configuration failed", e);
        }
    }

    ...
----

* UserService implementation in JHipster:

[source, java]
----
/**
 * Authenticate a user from the database.
 */
@Component("userDetailsService")
public class DomainUserDetailsService implements UserDetailsService {

    ...

    private final UserRepository userRepository;

    ...

    @Override
    @Transactional
    public UserDetails loadUserByUsername(final String login) {

        // Loading user from database

    }

    ...

----

== Authorities
* authorities = roles
* already used above in _SecurityConfiguration_:

[source, java]
----
    @Override
    public void configure(HttpSecurity http) throws Exception {
        http
            ...
            .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN)
            ...

    }
----

* good idea to define authorities in enum to use them in configuration classes:

[source, java]
----
/**
 * Constants for Spring Security authorities.
 */
public final class AuthoritiesConstants {

    public static final String ADMIN = "ROLE_ADMIN";

    public static final String USER = "ROLE_USER";

    public static final String ANONYMOUS = "ROLE_ANONYMOUS";

    private AuthoritiesConstants() {
    }
}
----

* in JHipster, authorities saved in database, hence retrieved in _DomainUserDetailsService_:

[source, java]
----
    private org.springframework.security.core.userdetails.User createSpringSecurityUser(String lowercaseLogin, User user) {
        if (!user.getActivated()) {
            throw new UserNotActivatedException("User " + lowercaseLogin + " was not activated");
        }
        List<GrantedAuthority> grantedAuthorities = user.getAuthorities().stream()
            .map(authority -> new SimpleGrantedAuthority(authority.getName()))
            .collect(Collectors.toList());
        return new org.springframework.security.core.userdetails.User(user.getLogin(),
            user.getPassword(),
            grantedAuthorities);
    }

----

== class SecurityContextHolder
* holds information about currently logged-in user, his authorities and user details
* examples in JHipster 1. storing user information after authentication:

[source, java]
----
public class UserJWTController {

    ...

    @PostMapping("/authenticate")
    @Timed
    public ResponseEntity<JWTToken> authorize(@Valid @RequestBody LoginVM loginVM) {

        UsernamePasswordAuthenticationToken authenticationToken =
            new UsernamePasswordAuthenticationToken(loginVM.getUsername(), loginVM.getPassword());

        Authentication authentication = this.authenticationManager.authenticate(authenticationToken);
        SecurityContextHolder.getContext().setAuthentication(authentication);
    ...
----

* examples in JHipster 2: retrieving login-string from _SecurityContextHolder_:

[source, java]
----
public final class SecurityUtils {
    ...

        /**
         * Get the login of the current user.
         *
         * @return the login of the current user
         */
        public static Optional<String> getCurrentUserLogin() {
            SecurityContext securityContext = SecurityContextHolder.getContext();
            return Optional.ofNullable(securityContext.getAuthentication())
                .map(authentication -> {
                    if (authentication.getPrincipal() instanceof UserDetails) {
                        UserDetails springSecurityUser = (UserDetails) authentication.getPrincipal();
                        return springSecurityUser.getUsername();
                    } else if (authentication.getPrincipal() instanceof String) {
                        return (String) authentication.getPrincipal();
                    }
                    return null;
                });
        }
----

* _getCurrentUserLogin()_ used to add user information to actions, for example logged-in user creates new set of data, it could need a creator field or the users email address to respond to this new content
* Every web-request is processed in its own thread. That is why the static method _SecurityContextHolder.getContext()_ retrieves the context of the currently logged-in user. _SecurityContextPersistenceFilter_ binds the _SecurityContext_ to the current thread of the current web request by using _SecurityContextRepository_. Hence, every request is processed in its own thread, in which the _SecurityContext_ holds only information about the currently logged-in user.

== Class AuthenticationProvider
* org.springframework.security.authentication.AuthenticationProvider
* interface
* *can* be implemented for *additional* custom authentication
* two methods:

[source,java]
----
Authentication authenticate(Authentication authentication) throws AuthenticationException;

boolean supports(Class<?> authentication);
----

* _supports()_ = what class of authorization is supported, for example _UsernamePasswordAuthenticationToken_
* _authenticate()_ = processing authentication, for example by using a database
* implementation of _AuthenticationProvider_ can simply be registered by declaring it a bean

== Security Interceptor
* stands between user requests and resources
* two variates:
** FilterSecurityInterceptor: filters HTTP requests by checking requests against the _@RequestMapping_ annotations
** MethodSecurityInterceptor: filters method invocations by checking requests against _@Secured_ annotations above methods

== CSRF
* Cross Site Request Forgery
* fundamental problem: browser using open session from "good" site to run requests from "bad" site to the good site
* example:
** browsing to banking website
** logging in and thus creating a session
** forget to log out or open another tab
** -> the session is still alive!
** open bad site
** bad site uses open session to send request to banking website, but with changed details
** banking site has no way of knowing that forged request is not intended by user
* solution: check where requests are coming from
* automatically secured when using Spring Security
* on frontend: need to send CSRF-token with every request
* that token send by server when loading page for the very first time, stored in browser and send back with every request
* token could change with every user or every couple of minutes, so malicious website cannot know / guess it
* JHipster: "Spring Security and Angular both have CSRF protection out-of-the-box, but unfortunately they don’t use the same cookies or HTTP headers! In practice, you have in fact no protection at all for CSRF attacks. Of course, we re-configure both tools so that they correctly work together." (https://www.jhipster.tech/security/[source])

== Encoding passwords
* never store user credentials in plain text!
* setup in JHipster already using best password encoder BCrypt:

[source, java]
----
public class SecurityConfiguration extends WebSecurityConfigurerAdapter {

    private final AuthenticationManagerBuilder authenticationManagerBuilder;

    private final UserDetailsService userDetailsService;

    ...

    @PostConstruct
    public void init() {
        try {
            authenticationManagerBuilder
                .userDetailsService(userDetailsService)
                .passwordEncoder(passwordEncoder());
        } catch (Exception e) {
            throw new BeanInitializationException("Security configuration failed", e);
        }
    }

    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }

    ...
----

* has to be used when registering a new user:

[source, java]
----
@Service
@Transactional
public class UserService {

    private final PasswordEncoder passwordEncoder;

    ...

    public User createUser(UserDTO userDTO) {
        User user = new User();
        user.setLogin(userDTO.getLogin().toLowerCase());
        user.setFirstName(userDTO.getFirstName());
        user.setLastName(userDTO.getLastName());
        user.setEmail(userDTO.getEmail().toLowerCase());
        user.setImageUrl(userDTO.getImageUrl());
        if (userDTO.getLangKey() == null) {
            user.setLangKey(Constants.DEFAULT_LANGUAGE); // default language
        } else {
            user.setLangKey(userDTO.getLangKey());
        }
        String encryptedPassword = passwordEncoder.encode(RandomUtil.generatePassword());
        user.setPassword(encryptedPassword);
        user.setResetKey(RandomUtil.generateResetKey());
        user.setResetDate(Instant.now());
        user.setActivated(true);
        if (userDTO.getAuthorities() != null) {
            Set<Authority> authorities = userDTO.getAuthorities().stream()
                .map(authorityRepository::findById)
                .filter(Optional::isPresent)
                .map(Optional::get)
                .collect(Collectors.toSet());
            user.setAuthorities(authorities);
        }
        userRepository.save(user);
        log.debug("Created Information for User: {}", user);
        return user;
    }

    ...
----

=== Salting Hashes
* problem: encrypted passwords could be attacked by creating huge amounts of hashed potential passwords (for example from dictionaries) and comparing these to saved encrypted passwords - attacker would get access to plain text password to try to log in on other websites
* solution: adding some random data to hash = salt
* every user has own salt (not one for all!)
* best solution for password encoder, BCrypt, does already add random salt when creating password

== LDAP Authentication
* https://directory.apache.org[Apache] provides both a server and a studio application to start an LDAP server and configuring it
* LDAP holds credentials and authorities, hence no other database for authorization needed
* connection to Spring Security via https://mvnrepository.com/artifact/org.springframework.security/spring-security-ldap[spring-security-ldap]
* https://spring.io/guides/gs/authenticating-ldap/[Most recent documentation]

= Authorization
* topics above mostly authentication
* authorization mentioned:

[source, java]
----
...
public class SecurityConfiguration extends WebSecurityConfigurerAdapter {
...

    @Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring()
            .antMatchers("/api/authenticate");
            .antMatchers(HttpMethod.OPTIONS, "/**")
            .antMatchers("/app/**/*.{js,html}")
            .antMatchers("/i18n/**")
            .antMatchers("/content/**")
            .antMatchers("/h2-console/**")
            .antMatchers("/swagger-ui/index.html")
            .antMatchers("/test/**");
    }

@Override
public void configure(HttpSecurity http) throws Exception {
    http
        .authorizeRequests()
        .antMatchers("/api/register").permitAll()
        .antMatchers("/api/activate").permitAll()
        .antMatchers("/api/authenticate").permitAll()
        .antMatchers("/api/account/reset-password/init").permitAll()
        .antMatchers("/api/account/reset-password/finish").permitAll()
        .antMatchers("/api/**").authenticated()
        .antMatchers("/management/health").permitAll()
        .antMatchers("/management/info").permitAll()
        .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN)
    .and()
        .apply(securityConfigurerAdapter());

}
----

* many possibilities:
** _hasAuthority()_
** _hasRole()_
** _hasAnyRole()_

== Authorization of methods
* on the backend, methods have to be guarded because of the danger of requests from modified clients
* enabling global method security:

[source, java]
----
@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true)
@Import(SecurityProblemSupport.class)
public class SecurityConfiguration extends WebSecurityConfigurerAdapter {
    ...
----

=== @PreAuthorize
* guards methods from access from unauthorized users
* evaluated *before* method is invoked

[source, java]
----
@PostMapping("/users")
@Timed
@PreAuthorize("hasRole(\"" + AuthoritiesConstants.ADMIN + "\")")
public ResponseEntity<User> createUser(@Valid @RequestBody UserDTO userDTO) throws URISyntaxException {
----

* _@PreAuthorize_ uses Spring expression language (SPEL)

=== _@PostAuthorize_
* evaluated *after* method is invoked, so return-object can be used for authorization
* guards methods against being called to get unauthorized data

[source, java]
----
@PostAuthorize("returnObject == 'something'")
public String blubber(String username) {
    //...
}
----

=== @RolesAllowed
* shorter version for _@PreAuthorize_ if the goal is to guard for access from wrong roles
* _@Secured_ and _@RolesAllowed_ identical functionality, however _@Secured_ Spring-specific while _@RolesAllowed_ is not

[source, java]
----
@RolesAllowed("ROLE_ADMIN, ROLE_USER")
----

=== @PreFilter
* filter collections that are passed into the method

=== @PostFilter
* filters a return collection

== Access Control
* security at domain level
* example: user A should view entities from user B, but not change them
* consists of Access Control Entries (ACE) form an Access Control List (ACL)
* to use Access Control, database needs extra tables
** ACL_CLASS stores class name of domain object
** ACL_SID identifies any principle and authority in the system
** ACL_OBJECT_IDENTITY stores information for each unique domain object
** ACL_ENTRY stores individual permission of users for each object
* pretty complex
* because many permissions are loaded, additional cache like EhCache can be used
* actual filtering done via _@PostAuthorize_
* other source: https://www.baeldung.com/spring-security-acl

= TLS
* encrypts data send between client and server
* create public key for application via terminal - in JHipster, nice stage separation done:
* _application-dev.yml_:

[source, properties]
----
# ===================================================================
# To enable SSL in development, uncomment the the "server.ssl" properties below.
#
# JHipster has generated a self-signed certificate, which will be used to encrypt traffic.
# As your browser will not understand this certificate, you will need to import it.
#
# Another (easiest) solution with Chrome is to enable the "allow-insecure-localhost" flag
# at chrome://flags/#allow-insecure-localhost
# ===================================================================
server:
    port: 8080
#    ssl:
#        key-store: classpath:config/tls/keystore.p12
#        key-store-password: password
#        key-store-type: PKCS12
#        key-alias: selfsigned
----

* _application-prod.yml_:
[sourece, properties]
----
# ===================================================================
# To enable SSL in production, generate a certificate using:
# keytool -genkey -alias cleanjhipster -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 443
#    ssl:
#        key-store: classpath:config/tls/keystore.p12
#        key-store-password: password
#        key-store-type: PKCS12
#        key-alias: cleanjhipster
#        # The ciphers suite enforce the security by deactivating some old and deprecated SSL cipher, this list was tested against SSL Labs (https://www.ssllabs.com/ssltest/)
#        ciphers: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 ,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA,TLS_RSA_WITH_CAMELLIA_256_CBC_SHA,TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA,TLS_RSA_WITH_CAMELLIA_128_CBC_SHA
# ===================================================================
----

* this is only the basic setup to use HTTPS - how to mandate usage of HTTPS, see https://www.baeldung.com/spring-channel-security-https[here]
